# Generated by Django 4.0.3 on 2022-04-19 05:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.TextField()),
                ('idNumber', models.TextField()),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('birthDate', models.DateField(default='date.today')),
                ('reservedate', models.DateTimeField(default='date.today')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
