# Generated by Django 4.0.3 on 2022-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=15)),
                ('idNumber', models.PositiveSmallIntegerField()),
                ('phoneNumber', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birthDate', models.DateField(default='date.today')),
            ],
        ),
    ]
