# Generated by Django 4.0.3 on 2022-04-18 10:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reserve_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
