# Generated by Django 4.0.3 on 2022-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reserve_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='fatherName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='idNumber',
            field=models.TextField(),
        ),
    ]
