# Generated by Django 4.0.3 on 2022-04-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reserve_docname_reserve_reservetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='reservetime',
        ),
    ]
