# Generated by Django 4.0.3 on 2022-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reserve_reservetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reservetime',
            field=models.TimeField(auto_now=True),
        ),
    ]
