# Generated by Django 4.0.3 on 2022-04-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reserve_reservetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='reservetime',
            field=models.TimeField(),
        ),
    ]
